spring:
  datasource:
    name: nothing
    url: jdbc:mysql://118.24.38.46:3306/nothing?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 521428Slly
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: mergeStat,config,slf4j
      max-active: 10000
      initial-size: 5
      max-wait: 60000
      min-idle: 3
      time-between-eviction-runs-millis: 18000000
      min-evictable-idle-time-millis: 1000000
      validation-query: SELECT1FROMDUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 100
      max-pool-prepared-statement-per-connection-size: 50
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: false
mybatis:
  mapper-locations: classpath:mapping/*.xml
server:
  port: 8081