spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/nothing?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 521428
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
server:
  port: 8080