spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: husen
    password: 521428
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory:
    listener:
      simple:
        concurrency: 2
        max-concurrency: 2
server:
  port: 8082